#cloud-config

write_files:
################################
# COMPOSE FILE FOR CQUEUE FRONTEND
################################
- path: /tmp/compose-cqueue-frontend-only
  content: |
    version: '2.0'
    services:
      rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
          - "15672:15672"  # management port
          - "5672:5672"   # amqp port
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

      redis:
        image: redis
        restart: always
        command: redis-server --appendonly yes
        ports:
          - "6379:6379"

      frontend:
        image: sztakilpds/cqueue_frontend:{{variables.CQUEUE_VERSION}}
        environment:
          - BROKER=amqp://guest:guest@rabbitmq:5672
          - RESULT_BACKEND=redis://redis:6379
        restart: always
        depends_on:
          - rabbitmq
          - redis
        links:
          - rabbitmq
        ports:
          - "8080:8080"
  permissions: '600'

##############################
# SCRIPT TO DOWNLOAD DOCKER CE
##############################
- path: /bin/install-docker-ce.sh
  content: |
    #!/bin/bash

    set -x
    echo "Downloading DOCKER CE starts."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce={{variables.DOCKER_VERSION}} docker-ce-cli={{variables.DOCKER_VERSION}} containerd.io
    echo "Downloading DOCKER CE finished."
  permissions: '755'


###################################
# SCRIPT TO DOWLOAND DOCKER COMPOSE
###################################
- path: /bin/install-docker-compose.sh
  content: |
    #!/bin/bash

    echo "Downloading DOCKER COMPOSE starts."
    set -x
    sudo curl -L https://github.com/docker/compose/releases/download/{{variables.DOCKER_COMPOSE_VERSION}}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    echo "Downloading DOCKER COMPOSE finished."
  permissions: '755'

runcmd:
# Install DOCKER CE
- /bin/install-docker-ce.sh
# Install DOCKER COMPOSE
- /bin/install-docker-compose.sh
# Launch cqueue master frontend
- docker-compose -f /tmp/compose-cqueue-frontend-only up -d
- echo "CQUEUE MASTER DEPLOYMENT DONE."
