#cloud-config

write_files:
##############################
# SCRIPT TO DOWNLOAD DOCKER CE
##############################
- path: /bin/install-docker-ce.sh
  content: |
    #!/bin/bash

    set -x
    echo "Downloading DOCKER CE starts."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce={{variables.DOCKER_VERSION}} docker-ce-cli={{variables.DOCKER_VERSION}} containerd.io
    echo "Downloading DOCKER CE finished."
  permissions: '755'

runcmd:
# Install DOCKER CE
- /bin/install-docker-ce.sh
# Launch CQueue worker
- docker run -d -e BROKER=amqp://guest:guest@{{getip(master)}}:5672 -e RESULT_BACKEND=redis://{{getip(master)}}:6379 --restart=always -v /var/run/docker.sock:/var/run/docker.sock sztakilpds/cqueue_worker:{{variables.CQUEUE_VERSION}}
- docker run -d -e BROKER=amqp://guest:guest@{{getip(master)}}:5672 -e RESULT_BACKEND=redis://{{getip(master)}}:6379 --restart=always -v /var/run/docker.sock:/var/run/docker.sock sztakilpds/cqueue_worker:{{variables.CQUEUE_VERSION}} --batch=true
- echo "CQUEUE WORKER DEPLOYMENT DONE."
