#cloud-config

write_files:

################################
# SCRIPT TO INSTALL JAVA
################################
- path: /bin/spark-install-java.sh
  content: |
    #!/bin/bash
    echo "Install JAVA starts."
    sudo add-apt-repository ppa:webupd8team/java -y
    sudo apt-get update
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get install oracle-java8-installer -y    
    echo "Install JAVA finished."
  permissions: '755'

################################
# SCRIPT TO INSTALL APACHE SPARK
################################
- path: /bin/spark-install-spark.sh
  content: |
    echo "Install SPARK starts."
    wget http://xenia.sote.hu/ftp/mirrors/www.apache.org/spark/spark-2.4.1/spark-2.4.1-bin-hadoop2.7.tgz -O /home/sparkuser/spark-2.4.1-bin-hadoop2.7.tgz
    tar zxvf /home/sparkuser/spark-2.4.1-bin-hadoop2.7.tgz  --directory /home/sparkuser
    mv /home/sparkuser/spark-2.4.1-bin-hadoop2.7 /home/sparkuser/spark
    rm /home/sparkuser/spark-2.4.1-bin-hadoop2.7.tgz
    echo "Install SPARK finished."
  permissions: '755'

################################
# SCRIPT TO SETUP SPARK CONFIG
################################
- path: /bin/spark-setup-config.sh
  content: |
    #!/bin/bash
    echo "Configure SPARK starts."
    cp /home/sparkuser/spark/conf/spark-env.sh.template /home/sparkuser/spark/conf/spark-env.sh
    masterip=`ifconfig | awk '/inet addr/{print substr($2,6)}' | grep -v 127.0.0.1 | head -n 1`
    echo "SPARK_MASTER_HOST='$masterip'" >> /home/sparkuser/spark/conf/spark-env.sh
    chown -R sparkuser:sparkuser /home/sparkuser/spark
    echo "Configure SPARK ends."
  permissions: '755'
  
runcmd:
#Install JAVA
- /bin/spark-install-java.sh
#Install SPARK
- /bin/spark-install-spark.sh
#Setup SPARK
- /bin/spark-setup-config.sh
#Launch SPARK
- su - sparkuser -c /home/sparkuser/spark/sbin/start-master.sh
- echo "SPARK DEPLOYMENT DONE."
