#cloud-config

write_files:

################################
# SCRIPT TO INSTALL JAVA
################################
- path: /bin/spark-install-java.sh
  content: |
    #!/bin/bash
    echo "Install JAVA starts."
    sudo add-apt-repository ppa:webupd8team/java -y
    sudo apt-get update
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    sudo apt-get install oracle-java8-installer -y    
    echo "Install JAVA finished."
  permissions: '755'

################################
# SCRIPT TO INSTALL APACHE SPARK
################################
- path: /bin/spark-install-spark.sh
  content: |
    #!/bin/bash
    set -x
    echo "Install SPARK starts."
    wget http://xenia.sote.hu/ftp/mirrors/www.apache.org/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz -O /usr/local/spark-2.3.1-bin-hadoop2.7.tgz
    tar zxvf /usr/local/spark-2.3.1-bin-hadoop2.7.tgz  --directory /usr/local
    rm /usr/local/spark-2.3.1-bin-hadoop2.7.tgz
    chown -R ubuntu:ubuntu /usr/local/spark-2.3.1-bin-hadoop2.7/*
    echo "Install SPARK finished."
  permissions: '755'

################################
# SCRIPT TO SETUP SPARK CONFIG
################################
- path: /bin/spark-setup-config.sh
  content: |
    #!/bin/bash
    echo "Configure SPARK starts."
    masterip=`ifconfig | awk '/inet addr/{print substr($2,6)}' | grep -v 127.0.0.1 | head -n 1`
    cp /usr/local/spark-2.3.1-bin-hadoop2.7/conf/spark-env.sh.template /usr/local/spark-2.3.1-bin-hadoop2.7/conf/spark-env.sh
    echo "SPARK_MASTER_HOST='$masterip'" >> /usr/local/spark-2.3.1-bin-hadoop2.7/conf/spark-env.sh
    chown ubuntu:ubuntu /usr/local/spark-2.3.1-bin-hadoop2.7/conf/spark-env.sh
    echo "Configure SPARK ends."
  permissions: '755'
  
  
runcmd:
#Install JAVA
- /bin/spark-install-java.sh
#Install SPARK
- /bin/spark-install-spark.sh
#Setup SPARK
- /bin/spark-setup-config.sh
#Launch SPARK
- ./usr/local/spark-2.3.1-bin-hadoop2.7/sbin/start-master.sh
- echo "SPARK DEPLOYMENT DONE."
