#cloud-config

write_files:
################################
# COMPOSE FILE FOR CQUEUE FRONTEND 
################################
- path: /tmp/compose-cqueue-frontend-only
  content: |
    version: '2.0'
    services:
      rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
          - "15672:15672"  # management port
          - "5672:5672"   # amqp port
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

      redis:
        image: redis
        restart: always
        command: redis-server --appendonly yes
        ports:
          - "6379:6379"

      frontend:
        image: sanyi86/cqueue_frontend
        environment:
          - BROKER=amqp://guest:guest@rabbitmq:5672
          - RESULT_BACKEND=redis://redis:6379
        restart: always
        depends_on:
          - rabbitmq
          - redis
        links:
          - rabbitmq
        ports:
          - "8080:8080"
  permissions: '600'

##############################
# SCRIPT TO DOWNLOAD DOCKER CE
##############################
- path: /bin/install-docker-ce.sh
  content: |
     #!/bin/bash
     set -x
     echo "Downloading DOCKER CE starts." 
     apt-get update
     apt-get install -y --no-install-recommends linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates curl software-properties-common
     echo deb http://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
     curl -fsSL https://apt.dockerproject.org/gpg | apt-key add -
     add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main" 
     apt-get update
     apt-get install -y docker-engine
     echo "DOCKER_OPTS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'" > /etc/default/docker
     service docker restart
     echo "Downloading DOCKER CE finished."
  permissions: '755'


###################################
# SCRIPT TO DOWLOAND DOCKER COMPOSE
###################################
- path: /bin/install-docker-compose.sh
  content: |
    #!/bin/bash
    echo "Downloading DOCKER COMPOSE starts." 
    set -x 
    sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose	
    echo "Downloading DOCKER COMPOSE finished."
  permissions: '755'

runcmd:
#Install DOCKER CE
- /bin/install-docker-ce.sh
#Install DOCKER COMPOSE
- /bin/install-docker-compose.sh
#Launch cqueue master frontend
- docker-compose -f /tmp/compose-cqueue-frontend-only up -d
- echo "CQUEUE MASTER DEPLOYMENT DONE."
