#cloud-config
runcmd:
    - ping {{ibget('node.resource.address', find_node_id(my_variables.targetnode))}} -c 5 > /tmp/ping-result.txt 2>&1
write_files:
- content: "{{my_variables.message}}\n"
  path: /tmp/message.txt
  permissions: '0644'

