#cloud-config
package_upgrade: false


write_files:

- path: /tmp/installation.sh
  content: |
    #!/bin/bash

    set -ex
    HADOOP_VERSION={{variables.HADOOP_VERSION}}
    CONSUL_VERSION={{variables.CONSUL_VERSION}}
    CONSUL_TEMPLATE_VERSION={{variables.CONSUL_TEMPLATE_VERSION}}

    echo "Creating HDUSER starts."
    adduser --disabled-password --gecos "" hduser
    chown -R hduser:hduser /home/hduser
    echo "Creating HDUSER finished."


    # Turn off unattended upgrade
    sed -i 's/APT::Periodic::Unattended-Upgrade "1";/APT::Periodic::Unattended-Upgrade "0";/g' /etc/apt/apt.conf.d/20auto-upgrades


    echo "Install requirement packages starts."
    # Wait for unattended upgrade
    while [[ `ps aufx | grep -v "grep" | grep "apt.systemd.daily" | wc -l` -gt 0 ]]; do
      echo "The unattended-upgrades are running..."
      sleep 1
    done

    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y openjdk-8-jdk openjdk-8-jre unzip
    echo "Install requirement packages starts."


    echo "Install HADOOP starts."
    wget -nc https://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz -O /home/hduser/hadoop-$HADOOP_VERSION.tar.gz
    tar -xzf /home/hduser/hadoop-$HADOOP_VERSION.tar.gz --directory /home/hduser
    mkdir /home/hduser/hadoop
    mv /home/hduser/hadoop-$HADOOP_VERSION/* /home/hduser/hadoop
    rm -r /home/hduser/hadoop-$HADOOP_VERSION.tar.gz /home/hduser/hadoop-$HADOOP_VERSION
    echo "Install HADOOP finished."


    echo "Install CONSUL starts."
    wget -nc "https://releases.hashicorp.com/consul/"$CONSUL_VERSION"/consul_"$CONSUL_VERSION"_linux_amd64.zip" -O /home/hduser/consul_"$CONSUL_VERSION"_linux_amd64.zip
    unzip -q /home/hduser/consul_"$CONSUL_VERSION"_linux_amd64.zip -d /home/hduser/consul/
    wget -nc "https://releases.hashicorp.com/consul-template/"$CONSUL_TEMPLATE_VERSION"/consul-template_"$CONSUL_TEMPLATE_VERSION"_linux_amd64.zip" -O /home/hduser/consul-template_"$CONSUL_TEMPLATE_VERSION"_linux_amd64.zip
    unzip -q /home/hduser/consul-template_"$CONSUL_TEMPLATE_VERSION"_linux_amd64.zip -d /home/hduser/consul/
    rm /home/hduser/consul_"$CONSUL_VERSION"_linux_amd64.zip /home/hduser/consul-template_"$CONSUL_TEMPLATE_VERSION"_linux_amd64.zip
    echo "Install CONSUL finished."


    echo -e "####################
    \e[92mInstallation DONE!!!\e[39m
    ####################"
  permissions: '755'

- path: /tmp/configuration.sh
  content: |
    #!/bin/bash

    set -ex
    MASTERIP=`hostname -I | col1`
    HOSTNAME=`hostname -s`


    echo "Configure HADOOP starts."
    touch /home/hduser/.bashrc
    chown hduser:hduser /home/hduser/.bashrc
    chown hduser:hduser /home/hduser/.bashrc
    echo export PATH="/home/hduser/hadoop/bin:$PATH" >> /home/hduser/.bashrc
    mv /tmp/hadoop/configs/* /home/hduser/hadoop/etc/hadoop
    mkdir /home/hduser/hadoop/logs
    echo "hadoop: lpds, admin" >> /home/hduser/hadoop/etc/hadoop/realm.properties
    echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre" >> /home/hduser/hadoop/etc/hadoop/hadoop-env.sh
    echo "export HADOOP_PID_DIR=/home/hduser/hadoop" >> /home/hduser/hadoop/etc/hadoop/hadoop-env.sh
    echo "export HADOOP_LOG_DIR=/home/hduser/hadoop/logs" >> /home/hduser/hadoop/etc/hadoop/hadoop-env.sh
    echo "{{getprivip('hadoop-master')}} hadoop-master" >> /etc/hosts
    chown -R hduser:hduser /home/hduser/hadoop
    echo "Configure HADOOP finished."


    su - hduser -c 'mkdir /home/hduser/consul/logs'
    su - hduser -c 'mkdir /home/hduser/consul/data'


    echo "Launch CONSUL starts."
    systemctl start consul.service
    systemctl start consul-template-hosts.service
    echo "Launch CONSUL finished."


    while [[ `cat /etc/hosts | grep 'Consul' | wc -l` -eq 0 ]]; do
      echo "Waiting for /etc/host modification..."
      sleep 1
    done


    echo -e "#####################
    \e[92mConfiguration DONE!!!\e[39m
    #####################"
  permissions: '755'

- path: /tmp/start-services.sh
  content: |
    #!/bin/bash

    set -ex
    MASTERIP=`hostname -I | col1`


    echo "Launch HADOOP starts."
    /home/hduser/hadoop/sbin/hadoop-daemon.sh start datanode
    echo "Launch HADOOP finished."


    echo -e "###################
    \e[92mServices STARTED!!!\e[39m
    ###################"
  permissions: '755'

- path: /tmp/hadoop/configs/hdfs-site.xml
  content: |
   <configuration>
    <property>
     <name>dfs.namenode.http-address</name>
      <value>{{getprivip('hadoop-master')}}:50070</value>
    </property>
    <property>
      <name>dfs.name.dir</name>
      <value>/tmp</value>
      <final>true</final>
    </property>
    <property>
       <name>dfs.permissions</name>
       <value>false</value>
    </property>
    <property>
      <name>dfs.datanode.du.reserved</name>
      <value>500000000</value>
    </property>
    <property>
      <name>dfs.client.use.datanode.hostname</name>
      <value>true</value>
    </property>
    <property>
      <name>dfs.datanode.use.datanode.hostname</name>
      <value>true</value>
    </property>
    <property>
      <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
      <value>false</value>
    </property>
   </configuration>
  permissions: '644'

- path: /tmp/hadoop/configs/core-site.xml
  content: |
      <configuration>
      <property>
        <name>fs.default.name</name>
        <value>hdfs://{{getprivip('hadoop-master')}}:9000</value>
      </property>
      </configuration>
  permissions: '644'

- path: /home/hduser/consul/hosts.ctmpl
  content: |
    127.0.0.1       localhost

    # The following lines are desirable for IPv6 capable hosts
    ::1     localhost ip6-localhost ip6-loopback
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

    # Consul managed
    {% raw %}
    {{range service "hadoop"}}
    {{.Address}} {{.Node}}{{end}}
    {% endraw %}
  permissions: '644'

- path: /home/hduser/consul/hadoop-slaves.ctmpl
  content: |
    {% raw %}
    {{range service "hadoop"}}
    {{.Node}}{{end}}
    {% endraw %}
  permissions: '644'

- path: /home/hduser/consul/service.json
  content: |
    {"service": {"name": "hadoop"}}
  permissions: '644'

- path: /etc/systemd/system/consul.service
  content: |
    [Unit]
    Description=consul agent
    Requires=network-online.target
    After=network-online.target

    [Service]
    Restart=on-failure
    ExecStart=/bin/bash -c "/home/hduser/consul/consul agent -retry-join {{ getprivip('hadoop-master') }} -data-dir=/home/hduser/consul/data -config-file=/home/hduser/consul/service.json -bind=$(hostname -I | col1) -client=$(hostname -I | col1) >> /home/hduser/consul/logs/consul.log 2>&1"
    ExecReload=/bin/kill -HUP $MAINPID
    KillSignal=SIGTERM

    [Install]
    WantedBy=multi-user.target
  permissions: '644'

- path: /etc/systemd/system/consul-template-hosts.service
  content: |
    [Unit]
    Description=consul for hosts file
    Requires=network-online.target
    After=network-online.target

    [Service]
    Restart=on-failure
    ExecStart=/bin/bash -c "/home/hduser/consul/consul-template -consul-addr $(hostname -I | col1):8500 -template \"/home/hduser/consul/hosts.ctmpl:/etc/hosts\" >> /home/hduser/consul/logs/consul-template-hosts.log 2>&1"
    ExecReload=/bin/kill -HUP $MAINPID
    KillSignal=SIGTERM

    [Install]
    WantedBy=multi-user.target
  permissions: '644'

runcmd:
- /tmp/installation.sh && /tmp/configuration.sh && su - hduser -c '/tmp/start-services.sh' && echo "HADOOP SLAVE DEPLOYMENT DONE." || echo -e "\e[91mPROBLEM OCCURED WITH THE INSTALLATION\e[39m"