#cloud-config

runcmd:
 - export DEBIAN_FRONTEND=noninteractive
 - apt-get update
 - apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg-agent software-properties-common
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
 - add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - apt-get update
 - apt-get install -y docker-ce={{variables.DOCKER_VERSION}} docker-ce-cli={{variables.DOCKER_VERSION}} containerd.io
 - wget --retry-connrefused -qO /tmp/swarm_join {{getip('master')}}:2375/v1.26/swarm
 - export TOKEN=$(grep -Eo 'SWMTKN-[[:alnum:]]*-[[:alnum:]]*-[[:alnum:]]*' /tmp/swarm_join | head -1)
 - docker swarm join --token $TOKEN {{getip('master')}}:2377
