#cloud-config

bootcmd:
 - echo deb http://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
 - apt-get update -qq
 - apt-get install apparmor -q -y --force-yes linux-generic-lts-vivid linux-image-extra-virtual-lts-vivid docker-engine
 - wget -nc https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
 - unzip -n consul_0.6.3_linux_amd64.zip
 - cp consul /usr/local/bin/

power_state:
 mode: reboot

runcmd:
 - export IP=$(hostname --ip-address);sed -i "s/<@@IP@@>/${IP}/g" /etc/default/docker
 - service consul restart ;sleep 3
 - export IP=$(hostname --ip-address);docker run --name=swarm -d swarm join --advertise=$IP:2375 consul://$IP:8500/

write_files:
 - path: /etc/init/consul.conf
   content: |
    description "Consul agent"
    start on runlevel [2345]
    stop on runlevel [!2345]
    respawn
    script
      if [ -f "/etc/service/consul" ]; then
        . /etc/service/consul
      fi
      # Make sure to use all our CPUs, because Consul can block a scheduler thread
      export GOMAXPROCS=`nproc`
      exec /usr/local/bin/consul agent \
        -retry-join {{getip(variables.target_node)}} -data-dir=/tmp/consul -bind=$(hostname --ip-address) -client=$(hostname --ip-address)\
        >>/var/log/consul.log 2>&1
    end script

 - path: /etc/default/docker
   content: |
     DOCKER_OPTS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --cluster-store=consul://<@@IP@@>:8500 --cluster-advertise=eth0:2375'

 - path: /etc/init/swarm.conf
   content: |
    start on filesystem and started docker
    stop on runlevel [!2345]
    respawn
    script
      /usr/bin/docker start -a swarm
    end script
