#cloud-config
write_files:
################################
# SCRIPT TO INSTALL AND DEPLOY DATAAVENUE
################################
- path: /bin/deploy-dataavenue.sh
  content: |
    #!/bin/bash
    echo "Deploying DATAAVENUE..."
    apt-get update
    git clone https://github.com/SZTAKI-LPDS/data-avenue.git /home/ubuntu/data-avenue
    mvn -f /home/ubuntu/data-avenue/pom.xml package
    cp /home/ubuntu/data-avenue/data-avenue.core.war/target/dataavenue.war /home/ubuntu/data-avenue/data-avenue.docker-compose/dataavenue/webapps/
    docker-compose -f /home/ubuntu/data-avenue/data-avenue.docker-compose/docker-compose.yml up -d
    echo "Done."
  permissions: '755'
packages:
 - git
 - maven
 - openjdk-8-jdk
 - docker-compose
runcmd:
#Run Dataavenue
- /bin/deploy-dataavenue.sh
- echo "DATAAVENUE NODE CONTEXTUALIZATION DONE."