#cloud-config
write_files:
################################
# SCRIPT TO INSTALL AND DEPLOY MINIO
################################
- path: /bin/deploy-minio.sh
  content: |
    #!/bin/bash
    echo "Deploying MINIO..."
    apt-get update
    docker run -d -v /mnt:/data -p 80:9000/tcp --name minio -e "MINIO_ACCESS_KEY={{variables.access_key}}" -e "MINIO_SECRET_KEY={{variables.secret_key}}" minio/minio server /data
    echo "Done."
  permissions: '755'
packages:
 - docker-compose
runcmd:
#Run MINIO
- /bin/deploy-minio.sh
- echo "STORAGE NODE CONTEXTUALISATION DONE"