#cloud-config

write_files:

############################
# SCRIPT TO CREATE OCCOUSER
############################
- path: /bin/create-user.sh
  content: |
    #!/bin/bash
    echo "Creating OCCOUSER starts."
    adduser --disabled-password --gecos "" occouser
    echo "Creating OCCOUSER finished."
  permissions: '755'

############################
# SCRIPT TO INSTALL ANACONDA
############################
- path: /bin/install-anaconda.sh
  content: |
    #!/bin/bash
    echo "Install ANACONDA starts."
    wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh  -O /home/occouser/Anaconda3-5.0.1-Linux-x86_64.sh
    su - occouser -c "bash /home/occouser/Anaconda3-5.0.1-Linux-x86_64.sh -b"

    su - occouser -c "echo export PATH="/home/occouser/anaconda3/bin:$PATH" >> /home/occouser/.profile"
    #source activate profile

    su - occouser -c "conda update conda -y"
    su - occouser -c "conda update anaconda -y"

    su - occouser -c "conda install -c conda-forge jupyter_contrib_nbextensions -y"
    su - occouser -c "jupyter contrib nbextension install --user"

    su - occouser -c "conda install tensorflow -y"
    su - occouser -c "conda install gensim -y"
    su - occouser -c "conda install keras -y"
    #conda activate envname
    echo "Install ANACONDA starts."
  permissions: '755'

##################################
# SCRIPT TO SETUP JUPYTER NOTEBOOK
##################################
- path: /bin/jupyter-config.sh
  content: |
    #!/bin/bash
    echo "Configure JUPYTER NOTEBOOK starts."
    su - occouser -c "~/anaconda3/bin/jupyter notebook --generate-config"
    echo "c = get_config()" >> /home/occouser/.jupyter/jupyter_notebook_config.py
    echo "c.NotebookApp.password = u'sha1:3ba4370be377:24644d24dcb81bcbd346114fcf9095ad7c1dd0ad'"  >> /home/occouser/.jupyter/jupyter_notebook_config.py
    masterip=`ifconfig | awk '/inet addr/{print substr($2,6)}' | grep -v 127.0.0.1 | head -n 1`
 
    su - occouser -c "mkdir tensorflow-demo"   
    su - occouser -c "wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/mnist1.png -O /home/occouser/tensorflow-demo/mnist1.png "
    su - occouser -c "wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/mnist3.png -O /home/occouser/tensorflow-demo/mnist3.png "
    su - occouser -c "wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/mnist4.png -O /home/occouser/tensorflow-demo/mnist4.png "
    su - occouser -c "wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/sztaki_logo_angol_kek.png -O /home/occouser/tensorflow-demo/sztaki_logo_angol_kek.png"
    su - occouser -c "wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/requirements.txt -O /home/occouser/tensorflow-demo/requirements.txt"
    su - occouser -c " wget https://gitlab.com/lpds-public/occopus-ml/raw/master/python-keras-tensorflow-stack/TensorFlowDemoWithPictures.ipynb -O /home/occouser/tensorflow-demo/TensorFlowDemoWithPictures.ipynb"
    su - occouser -c "/home/occouser/anaconda3/bin/conda config --add channels conda-forge "
    su - occouser -c "/home/occouser/anaconda3/bin/conda create -n tensorflow --file /home/occouser/tensorflow-demo/requirements.txt -y"
    su - occouser -c "/home/occouser/anaconda3/bin/conda init bash"
    su - occouser -c "/home/occouser/anaconda3/bin/conda activate tensorflow"
    su - occouser -c "~/anaconda3/bin/jupyter notebook --ip=$masterip --port=8888 >> /home/occouser/jupyter.log &"
    echo "Configure JUPYTER NOTEBOOK finished."
  permissions: '755'


runcmd:
#Create USER
- /bin/create-user.sh
#Install ANACONDA
- /bin/install-anaconda.sh
#Install JUPYTER NOTEBOOK
- /bin/jupyter-config.sh
- echo "DEPLOYMENT DONE."
