#cloud-config

runcmd:
 - apt-get update
 - apt-get install -y --no-install-recommends linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates curl software-properties-common
 - echo deb http://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
 - curl -fsSL https://apt.dockerproject.org/gpg | apt-key add -
 - add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
 - apt-get update
 - apt-get install -y docker-engine
 - echo "DOCKER_OPTS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'" > /etc/default/docker
 - service docker restart
 - export IP=$(hostname --ip-address)
 - docker swarm init --advertise-addr=$IP
